// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springsource.showcases.pizzashop.domain;

import org.springframework.beans.factory.annotation.Configurable;
import org.springsource.showcases.pizzashop.domain.Pizza;

privileged aspect Pizza_Roo_Configurable {
    
    declare @type: Pizza: @Configurable;
    
}
